TrajectoryPlannerROS:
  max_vel_x: 5.3
  min_vel_x: 0.5

  max_vel_y: 0  # zero for a differential drive robot
  min_vel_y: 0

  max_vel_theta: 0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.1
  escape_vel: -1
  acc_lim_x: 1.5
  acc_lim_y: 0.0  # zero for a differential drive robot
  acc_lim_theta: 0.5

  holonomic_robot: false
  yaw_goal_tolerance: 0.5 # about 24 degrees
  xy_goal_tolerance: 0.5  # 50 cm
  latch_xy_goal_tolerance: false
  pdist_scale: 0.6 # default 0.8
  gdist_scale: 0.8 # default 0.4
  meter_scoring: false

  heading_lookahead: 5
  heading_scoring: false
  heading_scoring_timestep: 20
  occdist_scale: 0.01
  oscillation_reset_dist: 0.05
  publish_cost_grid_pc: false


  sim_time: 20
  sim_granularity: 0.1
  angular_sim_granularity: 0.1
  vx_samples: 20
  vy_samples: 0  # zero for a differential drive robot
  vtheta_samples: 20
  dwa: false


