plugins:
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: obstacles, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_range: 10
raytrace_range: 15
footprint: [[-2.5, -1.5], [2.5, -1.5], [2.5, 1.5], [-2.5,1.5]]
#robot_radius: ir_of_robot
#inflation_radius: 10.0
#cost_scaling_factor: 10
obstacles:
  observation_sources: scan

  scan: {sensor_frame: velodyne, data_type: LaserScan, topic: ["/rowbot/scan"], marking: true, clearing: true}

inflation_layer:
  inflation_radius: 4
  cost_scaling_factor: 1
  enabled: true
