


DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.05
  max_vel_y: 0
  min_vel_y: 0
  min_trans_vel: 0.3
  max_trans_vel : 1
  max_rot_vel: 0.4
  min_rot_vel: 0.1

  yaw_goal_tolerance: 0.4
  xy_goal_tolerance: 1
  latch_xy_goal_tolerance: true

  sim_time: 10
  sim_granularity: 0.1
  vx_samples: 10
  vy_samples: 0
  vth_samples: 20

  path_distance_bias: 0
