planner_frequency: 5
planner_patience: 5.0
oscillation_timeout: 0
recovery_behavior_enabled: false
base_local_planner: "base_local_planner/TrajectoryPlannerROS" #"dwa_local_planner/DWAPlannerROS"

base_global_planner: "global_planner/GlobalPlanner" #alternatives: global_planner/GlobalPlanner,
controller_frequency: 10
